CI/CD changes
Changement :
   valider même si tous les tests ne sont pas passés mais notifier leur erreur. Ici les test ne sont pas encore fait

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,8 +35,8 @@ jobs:
       - name: Run lint (optional, if configured)
         run: npx turbo run lint || echo "No lint step defined"
 
-      - name: Run tests
-        run: npx turbo run test
+      - name: Run tests (non bloquant)
+        run: npx turbo run test || echo "Some tests failed or are missing"
 
       - name: Run build
         run: npx turbo run build
